### ISSUE TITLE
[Bug] Side light bars doesn't turn on after awake from sleep

### ISSUE THREAD

**Issue by dom0** [jincao1/qmk_firmware#4]
### Describe the Bug

As in the title, when keyboard awake from sleep, side led bars doesn't turn on.
The bug is reproducible in rf24 and bluetooth mode, to turn them on again you have to trigger events involvings bars (eg. view battery status or enable caps lock) 

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by jincao1** [comment]
@dom0 which side light animation are you using?

**Comment by dom0** [comment]
Thanks for the quick reply... I'm using simply fixed white color (third animation cycling with Fn+M+Left). Reading your comment i just tried the first one (rainbow) and it works as aspected.

Notes: 
 - the bug with fixed color is systematic
 - my keybord model is Air75 v2

**Comment by jincao1** [comment]
Try and see if this fixes it.

[nuphy_air75_v2_ansi_via-test.zip](https://github.com/user-attachments/files/15848286/nuphy_air75_v2_ansi_via-test.zip)

**Comment by dom0** [comment]
Sorry but your test build doesn't fix the issue

**Comment by jincao1** [comment]
[nuphy_air75_v2_ansi_via_v1.3.0.1-test.bin.zip](https://github.com/user-attachments/files/15854868/nuphy_air75_v2_ansi_via_v1.3.0.1-test.bin.zip)

This one should fix it.

**Comment by dom0** [comment]
The latest build fixes the problem. Thank you for your effort on this amazing firmware
