### ISSUE TITLE
Battery notification question

### ISSUE THREAD

**Issue by godzinilla** [jincao1/qmk_firmware#6]
### Issue Description

Hello,

I am looking for an explanation what really the battery notification means and can't find this information nowhere.

In this moment F4 and 9 is lighted on in yellowish-greenish color, together with the left bar. For the BT connection my Windows 11 shows that there is 50% battery left. The keyboard indicator shows the same values for RF and BT mode.
I've assuming that for the XY values, the F-rows corresponding the X value and the number rows are the Y value? It is mean that my battery is around 49% now?

On the official firmware the indicator is only on the left bar.

I am using the newest beta firmware, 1.3.0.1-beta.

**Comment by jincao1** [comment]
That is correct. F4+9 is 49%.

**Comment by godzinilla** [comment]
Thank you for the explanation :)
