### ISSUE TITLE
How the sleep modes works and how to edit the timeouts

### ISSUE THREAD

**Issue by godzinilla** [jincao1/qmk_firmware#8]
Hello.
I have another question about the firmware.
Recently I've messed something and my keyboard goes to sleep mode after about 30 seconds (which is waaay to short).
I have these two buttons configured:
SLEEP MODE
SLEEP TIMEOUT

For SLEEP MODE there are three modes: green, yellow and red. From my testing I found that:
- GREEN - enables sleep mode; keyboard is entering sleep mode after certain time (30s in my case) and reconnecting after pressing any button,
- YELLOW - enables lights off mode; keyboard disabling the lights after certain time (30s in my case) and enabling after pressing any button; no sleep mode,
- RED - sleep mode and lights off mode disabled.

Do you have anything to add about these three modes?

What about the button SLEEP TIMEOUT (and btw the LINK TIMEOUT)? I did not noticed any reactions by the keyboard after pressing these buttons.

**Comment by godzinilla** [comment]
And additionally I've found that sometimes in YELLOW mode the keys backlight is not powering on but the side lights are.

**Comment by godzinilla** [comment]
And now without any changes by my side keyboard is not activating mentioned modes after 30 seconds... What is going on?

**Comment by jincao1** [comment]
> Hello. I have another question about the firmware. Recently I've messed something and my keyboard goes to sleep mode after about 30 seconds (which is waaay to short). I have these two buttons configured: SLEEP MODE SLEEP TIMEOUT
> 
> For SLEEP MODE there are three modes: green, yellow and red. From my testing I found that:
> 
>     * GREEN - enables sleep mode; keyboard is entering sleep mode after certain time (30s in my case) and reconnecting after pressing any button,
> 
>     * YELLOW - enables lights off mode; keyboard disabling the lights after certain time (30s in my case) and enabling after pressing any button; no sleep mode,
> 
>     * RED - sleep mode and lights off mode disabled.
> 
> 
> Do you have anything to add about these three modes?
> 
> What about the button SLEEP TIMEOUT (and btw the LINK TIMEOUT)? I did not noticed any reactions by the keyboard after pressing these buttons.

`Fn + M + S` toggles the sleep timeout (unless you remapped the key). Default is `360s` or 6 minutes. If you toggled it, you might've switched it to `30s`. Toggle it again to flip it back to 6 min or restart the keyboard.

> And additionally I've found that sometimes in YELLOW mode the keys backlight is not powering on but the side lights are.

Which animation mode are you using? I had a person report the same before but I couldn't replicate it.

**Comment by godzinilla** [comment]
> `Fn + M + S` toggles the sleep timeout (unless you remapped the key). Default is `360s` or 6 minutes. If you toggled it, you might've switched it to `30s`. Toggle it again to flip it back to 6 min or restart the keyboard.

I've remaped the button. But there is no indicator which value is set, right? Only these two values?

> Which animation mode are you using? I had a person report the same before but I couldn't replicate it.

Not sure 100% right now because I've currently switched to other firmware. It was set to full white but there is a lot of effects which set to white color acts the same - they just stock white without any reactions when pressed (or not).

**Comment by jincao1** [comment]
No, there are no indicators. I should unmap that button, but it's pretty obvious it's toggled since the board sleeps much earlier.
Yes, there's only two modes as I used it early on for debugging. If it's not the 30s then it's the 360s, nothing in between.

As for the LED, I wonder if the hardware has slightly different timings and whatnot between different boards. I assumed you had a static colour which didn't flush the LED buffer on wake but I did make the change to set it to black temporarily so it forces a flush. Interesting it doesn't work on some. It works for me when I last tried (a while ago).

**Comment by godzinilla** [comment]
> No, there are no indicators. I should unmap that button, but it's pretty obvious it's toggled since the board sleeps much earlier. Yes, there's only two modes as I used it early on for debugging. If it's not the 30s then it's the 360s, nothing in between.

So only two time options and the behaviour of color modes is correct? It is OK to have this function and would be great to have some indicator of selected timeout value ;)

> As for the LED, I wonder if the hardware has slightly different timings and whatnot between different boards. I assumed you had a static colour which didn't flush the LED buffer on wake but I did make the change to set it to black temporarily so it forces a flush. Interesting it doesn't work on some. It works for me when I last tried (a while ago).

The Nuphy firmware is quite mysterious but not in the good way tbh ;) I will test the adi4068 firmware for couple days and switch back to yours for further testing. Interesting that I've loaded the modes jsons saved from your firmware without problems (but I must to switch the main json for keys layout due to some differences in custom functions) but when I tried to load the modes saved from the original firmware the QMK refused to use it.

**Comment by jincao1** [comment]
There's no indicator for the sleep timeout because it was meant for my debugging usage. Hence should've removed it but just left it in an awkward layer most people won't press.

Yea, go try Adi's firmware, I think ryodeushii also has an Air75 firmware too now. Both those are much more gamer geared and have a bunch more features. I personally just use mine for work so haven't gone around doing fancy stuff to it.
